name: Octonomy TF Modules Publish

on: 
    workflow_dispatch:
    push:
        branches:
            - main
            - new-main

jobs:
  PublishModule:
    runs-on: ubuntu-latest

    steps:
      - name: Git Code Checkout
        uses: actions/checkout@v4

      - name: zip the oc-tf-modules
        run: |
          zip -r oc-tf-modules.zip ./ -x "*.git*" "*.DS_Store"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@0e613a0980cbf65ed5b322eb7a1e075d28913a83
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "eu-central-1"

      - name: Upload zipped modules to S3
        run: |
          if aws s3 cp oc-tf-modules.zip s3://qs-tf-modules/oc-tf-modules.zip; then
            echo "Upload to S3 bucket successful"
          else
            echo "Upload to S3 bucket failed" && exit 1
          fi

      - name: Cleanup Workspace
        if: always()
        run: |
          rm -f oc-tf-modules.zip
          echo "Cleaned up workspace by removing the zip file."
